name: 'Bump Version'
description: 'Bump version in package.json and version.json files'
inputs:
  bump-type:
    description: 'Type of version bump: major, minor, or patch'
    required: false
    default: 'patch'
  working-directory:
    description: 'Working directory containing package.json'
    required: false
    default: '.'

outputs:
  new-version:
    description: 'The new version after bump'
    value: ${{ steps.bump.outputs.new_version }}
  old-version:
    description: 'The old version before bump'
    value: ${{ steps.bump.outputs.old_version }}

runs:
  using: 'composite'
  steps:
    - name: Bump version
      id: bump
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Get current version
        OLD_VERSION=$(node -p "require('./package.json').version")
        echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
        
        # Bump version using npm
        npm version ${{ inputs.bump-type }} --no-git-tag-version
        
        # Get new version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        
        # Update version.json if exists
        if [ -f "static/version.json" ]; then
          node -e "
            const fs = require('fs');
            const v = JSON.parse(fs.readFileSync('static/version.json'));
            v.version = '$NEW_VERSION';
            v.buildDate = new Date().toISOString();
            fs.writeFileSync('static/version.json', JSON.stringify(v, null, 2));
          "
          echo "Updated static/version.json to $NEW_VERSION"
        fi
        
        echo "Bumped version from $OLD_VERSION to $NEW_VERSION"
